FIELDS_CONSTRAINTS = {
    'min_port': 1,
    'max_port': 65535,
    'max_system_id_length': 16,
    'max_password_length': 9,
    'max_system_type_length': 13,
    'max_addr_ton_length': 1,
    'max_addr_npi_length': 1,
    'max_source_addr_ton_length': 1,
    'max_source_addr_npi_length': 1,
    'max_dest_addr_ton_length': 1,
    'max_dest_addr_npi_length': 1,
    'max_service_type_length': 6,
    'max_message_text_length': 160,
    'max_address_length': 15,
}
