# Generated by Django 3.2.11 on 2022-01-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(max_length=50, unique=True)),
                ('systemId', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=9)),
                ('port', models.IntegerField()),
                ('systemType', models.CharField(max_length=13)),
                ('useSSL', models.BooleanField()),
                ('addrTON', models.IntegerField()),
                ('addrNPI', models.IntegerField()),
                ('reconnect', models.BooleanField()),
                ('isDone', models.BooleanField(default=False)),
                ('isBound', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.CharField(max_length=160)),
                ('sourceAddr', models.CharField(max_length=15)),
                ('sourceAddrTON', models.IntegerField()),
                ('sourceAddrNPI', models.IntegerField()),
                ('destAddr', models.CharField(max_length=15)),
                ('destAddrTON', models.IntegerField()),
                ('destAddrNPI', models.IntegerField()),
                ('serviceType', models.CharField(max_length=6)),
                ('bulkSubmitEnable', models.BooleanField()),
                ('bulkSubmitTimes', models.IntegerField()),
                ('dataCoding', models.IntegerField()),
                ('submitMode', models.CharField(max_length=20)),
                ('readyToBeSent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientmodel')),
            ],
        ),
    ]
