# Generated by Django 4.0.1 on 2022-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=8, unique=True)),
                ('system_id', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=9)),
                ('port', models.IntegerField()),
                ('system_type', models.CharField(max_length=13)),
                ('use_ssl', models.BooleanField()),
                ('addr_ton', models.IntegerField(max_length=1)),
                ('addr_npi', models.IntegerField(max_length=1)),
                ('reconnect', models.BooleanField()),
            ],
        ),
    ]
