# Generated by Django 4.0.1 on 2022-01-20 14:26

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(default=api.models.generate_unique_id_for_bind, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('systemId', models.CharField(max_length=16)),
                ('hostname', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=9)),
                ('port', models.IntegerField()),
                ('systemType', models.CharField(max_length=13)),
                ('useSSL', models.BooleanField()),
                ('addrTON', models.IntegerField()),
                ('addrNPI', models.IntegerField()),
                ('reconnect', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionId', models.CharField(default=api.models.generate_unique_id_for_message, max_length=8, unique=True)),
                ('host', models.CharField(max_length=50, unique=True)),
                ('messageText', models.CharField(max_length=160)),
                ('sourceAddr', models.CharField(max_length=15)),
                ('sourceAddrTON', models.IntegerField()),
                ('sourceAddrNPI', models.IntegerField()),
                ('destAddr', models.CharField(max_length=15)),
                ('destAddrTON', models.IntegerField()),
                ('destAddrNPI', models.IntegerField()),
                ('serviceType', models.CharField(max_length=6)),
                ('bulkSubmitEnable', models.BooleanField()),
                ('bulkSubmitTimes', models.IntegerField()),
                ('dataCoding', models.IntegerField()),
                ('submitMode', models.CharField(max_length=20)),
            ],
        ),
    ]
