# Generated by Django 4.0.1 on 2022-01-19 18:46

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sessionId',
            field=models.CharField(default=api.models.generate_unique_id_for_message, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='submitMode',
            field=models.CharField(max_length=20),
        ),
    ]
